apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: davtha/fastapi
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "10.43.180.251"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "" # cf .env conf
            - name: POSTGRES_PASSWORD
              value: "" # cf .env conf
            - name: POSTGRES_DB
              value: "spotify_database"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080 